import { Alegreya_Sans_SC   } from 'next/font/google';
import { Pompiere } from 'next/font/google'; 
import { Great_Vibes, Playfair_Display } from 'next/font/google';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { LoadingProvider } from './contex/LoadingContext';
import GlobalLoader from './components/GlobalLoader';
import Head from 'next/head'; 

const pompiere = Pompiere({
  subsets: ['latin'],
  weight: [ '400'],
  variable: '--font-allura',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-montserrat',
});


const alegreyaSansSC = Alegreya_Sans_SC({ 
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '800', '900'], 
  variable: '--font-alegreya-sans-sc',
});

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-greatVibes',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-playfair',
});

export const metadata = {
  title: 'Маникюрный Салон',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
<html lang="ru" className={`${pompiere.variable} ${alegreyaSansSC.variable} ${greatVibes.variable} ${playfair.variable} ${montserrat.variable}`}>
            <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Playwrite+Danmark+Loopet&display=swap" rel="stylesheet" />
      </Head>
      <body className="antialiased font-sans">
        <LoadingProvider>
          <GlobalLoader />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}